//! Model catalog — built-in model registry and user-configurable extensions.
//!
//! The built-in models are generated by `cargo xtask generate-models` from
//! `OpenRouter`'s public model list, with manual overrides for thinking support
//! and compatibility flags stored in `rho-ai/model-overrides.json`.
//!
//! Users can extend or override the built-in catalog via provider config in
//! `~/.rho/config.toml` (dedicated subscriptions, local models, etc.).

use std::sync::LazyLock;

use crate::types::StreamUsage;

/// Cost information for a model, in USD per million tokens.
#[derive(Debug, Clone, Default)]
pub struct ModelCost {
    /// Cost per million input tokens.
    pub input: f64,
    /// Cost per million output (completion) tokens.
    pub output: f64,
    /// Cost per million cached-read input tokens (prompt caching).
    pub cache_read: f64,
    /// Cost per million cache-write input tokens (prompt caching).
    pub cache_write: f64,
}

impl ModelCost {
    /// Compute the USD cost of a usage record from these per-million prices.
    ///
    /// Splits input tokens into cache-hit and fresh reads, prices cache hits
    /// at the discounted `cache_read` rate (falling back to the full input
    /// rate when the provider reports no cache-read price), and adds output
    /// tokens at the output rate.
    ///
    /// Returns `None` when pricing is unavailable so callers can distinguish
    /// "priced" from "unpriced". Negative prices are `OpenRouter` sentinels for
    /// "price unknown" (e.g. router models like `openrouter/auto` return
    /// `prompt: "-1"`), and are treated as unavailable rather than negative
    /// cost.
    #[must_use]
    #[allow(clippy::cast_precision_loss)] // token counts never approach 2^52
    pub fn cost_for(&self, usage: &StreamUsage) -> Option<f64> {
        if self.input < 0.0 || self.output < 0.0 {
            return None;
        }
        // Clamp cached to input in case a provider over-reports.
        let cached = usage.cached_tokens.min(usage.input_tokens);
        let fresh_input = usage.input_tokens - cached;
        // Price cache reads at cache_read if reported, else at full input rate
        // (a missing field should not silently zero-out cache cost).
        let cache_rate = if self.cache_read > 0.0 {
            self.cache_read
        } else {
            self.input
        };
        let cost = (fresh_input as f64 * self.input
            + cached as f64 * cache_rate
            + usage.output_tokens as f64 * self.output)
            / 1_000_000.0;
        Some(cost)
    }

    /// Whether this entry carries usable (non-sentinel) pricing.
    ///
    /// `OpenRouter` uses negative prices as an "unknown" sentinel (e.g. router
    /// models like `openrouter/auto` carry `prompt: "-1"`). Such entries are
    /// not usable for cost computation and should be skipped during model
    /// resolution. A legitimately free model reports `0.0`, not negative.
    #[must_use]
    pub fn is_priced(&self) -> bool {
        self.input >= 0.0 && self.output >= 0.0
    }
}

/// Input modalities supported by a model.
#[derive(Debug, Clone, Default)]
pub struct ModelInput {
    /// Whether text input is supported.
    pub text: bool,
    /// Whether image input is supported.
    pub image: bool,
}

/// Thinking/reasoning capability of a model.
#[derive(Debug, Clone, Default)]
pub struct ModelThinking {
    /// Whether this model supports extended thinking / chain-of-thought.
    pub supported: bool,
    /// How to request thinking from this model (e.g. `"reasoning"`, `"reasoning_effort"`).
    /// `None` means the default provider behavior.
    pub format: Option<String>,
}

/// A single model entry in the catalog.
#[derive(Debug, Clone)]
pub struct Model {
    /// Unique model identifier (e.g. `"anthropic/claude-sonnet-4"`).
    pub id: String,
    /// Human-readable display name (e.g. `"Claude Sonnet 4"`).
    pub name: String,
    /// Provider slug (e.g. `"anthropic"`, `"openai"`, `"deepseek"`).
    pub provider: String,
    /// Maximum context window in tokens.
    pub context_window: u64,
    /// Maximum completion (output) tokens per request.
    pub max_tokens: u64,
    /// Supported input modalities.
    pub input: ModelInput,
    /// Cost per million tokens.
    pub cost: ModelCost,
    /// Thinking/reasoning capability.
    pub thinking: ModelThinking,
}

impl Model {
    /// Compute the USD cost of a usage record from this model's pricing.
    ///
    /// Convenience wrapper around [`ModelCost::cost_for`]. Returns `None` when
    /// the catalog has no usable pricing for this model (sentinel/unknown).
    #[must_use]
    pub fn cost_for(&self, usage: &StreamUsage) -> Option<f64> {
        self.cost.cost_for(usage)
    }
}

/// Default model used when nothing is configured and `RHO_MODEL` is not set.
///
/// Picked as the best general-purpose coding model available via `OpenRouter`.
pub const DEFAULT_MODEL_ID: &str = "anthropic/claude-sonnet-4";

/// The model catalog — built-in models plus optional user extensions.
#[derive(Debug, Clone)]
pub struct Catalog {
    /// All models in the catalog (built-in plus user extensions).
    models: Vec<Model>,
}

/// Lazily-initialized built-in model list, shared by all lookups so the hot
/// path (per-iteration cost enrichment) never reallocates the catalog.
static BUILT_IN: LazyLock<Vec<Model>> = LazyLock::new(crate::catalog_generated::built_in_models);

impl Default for Catalog {
    fn default() -> Self {
        Self::new()
    }
}

impl Catalog {
    /// Look up a built-in model by ID without allocating a full catalog.
    ///
    /// Returns a static reference into the lazily-initialized built-in list.
    /// Prefer this over `Catalog::new().find(...)` in hot paths.
    #[must_use]
    pub fn find_built_in(id: &str) -> Option<&'static Model> {
        BUILT_IN.iter().find(|m| m.id == id)
    }

    /// Resolve a model for pricing, tolerating native-provider bare ids.
    ///
    /// Resolution order:
    /// 1. Exact id match (`OpenRouter` `provider/model` ids).
    /// 2. Unique basename match — entries whose id suffix (after the last `/`)
    ///    equals `model_id`. Resolves a bare native id like `gpt-4o-2024-08-06`
    ///    to `openai/gpt-4o-2024-08-06` when unambiguous.
    /// 3. Provider-hinted basename — when multiple match and `hint` matches one
    ///    entry's provider slug, use it.
    ///
    /// Returns `None` when ambiguous without a hint, so the caller surfaces an
    /// honest "cost n/a" rather than guessing. Sentinel-priced entries are
    /// skipped in the basename path. Phase 2 will thread a provider hint
    /// through `route_response` for disambiguation.
    #[must_use]
    pub fn resolve(hint: Option<&str>, model_id: &str) -> Option<&'static Model> {
        Self::resolve_in(hint, model_id, &BUILT_IN)
    }

    /// Resolution core over an arbitrary model slice.
    ///
    /// Factored out of [`resolve`](Self::resolve) so the basename and
    /// provider-hint disambiguation paths are unit-testable with synthetic
    /// data (the built-in catalog currently has no ambiguous basenames).
    fn resolve_in<'a>(
        hint: Option<&str>,
        model_id: &str,
        models: &'a [Model],
    ) -> Option<&'a Model> {
        // 1. Exact id match.
        if let Some(m) = models.iter().find(|m| m.id == model_id) {
            return Some(m);
        }
        // 2/3. Basename = segment after the last '/'; a bare id is its own basename.
        let basename = model_id.rsplit_once('/').map_or(model_id, |(_, base)| base);
        let mut hits: Vec<&Model> = models
            .iter()
            .filter(|m| {
                m.id.rsplit_once('/')
                    .is_some_and(|(_, base)| base == basename)
                    && m.cost.is_priced()
            })
            .collect();
        match hits.len() {
            0 => None,
            1 => hits.pop(),
            _ => hint.and_then(|h| hits.into_iter().find(|m| m.provider == h)),
        }
    }
    /// Create a catalog from the built-in model list only.
    pub fn new() -> Self {
        Self {
            models: crate::catalog_generated::built_in_models(),
        }
    }

    /// Create a catalog with additional user-defined models merged on top.
    ///
    /// User models with the same `id` replace built-in entries.
    pub fn with_user_models(user_models: Vec<Model>) -> Self {
        let mut models = crate::catalog_generated::built_in_models();
        for user in user_models {
            if let Some(existing) = models.iter_mut().find(|m| m.id == user.id) {
                *existing = user;
            } else {
                models.push(user);
            }
        }
        Self { models }
    }

    /// All models in the catalog.
    pub fn models(&self) -> &[Model] {
        &self.models
    }

    /// Find a model by its exact ID.
    pub fn find(&self, id: &str) -> Option<&Model> {
        self.models.iter().find(|m| m.id == id)
    }

    /// Find models by provider slug.
    pub fn by_provider(&self, provider: &str) -> Vec<&Model> {
        self.models
            .iter()
            .filter(|m| m.provider == provider)
            .collect()
    }

    /// Search models by a case-insensitive substring match on ID or name.
    pub fn search(&self, query: &str) -> Vec<&Model> {
        let query = query.to_lowercase();
        self.models
            .iter()
            .filter(|m| {
                m.id.to_lowercase().contains(&query) || m.name.to_lowercase().contains(&query)
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_contains_models() {
        let catalog = Catalog::new();
        assert!(!catalog.models().is_empty());
    }

    #[test]
    fn find_existing_model() {
        let catalog = Catalog::new();
        // Pick a model we know exists in OpenRouter.
        let model = catalog.find("anthropic/claude-sonnet-4");
        assert!(model.is_some());
        let m = model.unwrap();
        assert_eq!(m.provider, "anthropic");
        assert!(m.context_window > 0);
    }

    #[test]
    fn default_model_context_window_capped_to_standard() {
        // The default model is served via the synthesized OpenRouter provider,
        // which routes to BYOK backends (Vertex/Bedrock) that cap Claude Sonnet
        // 4 at its standard 200K window — NOT the 1M beta OpenRouter
        // advertises. The catalog must reflect the usable window so the agent
        // loop doesn't over-pack context and fail with
        // `input + max_tokens > context_limit`. See `model-overrides.json` and
        // `xtask` for the cap mechanism. This test guards against an
        // accidental regeneration that drops the override.
        let catalog = Catalog::new();
        let m = catalog
            .find(crate::catalog::DEFAULT_MODEL_ID)
            .expect("default model must be in catalog");
        assert_eq!(
            m.context_window, 200_000,
            "default model context_window must be capped to the standard 200K, \
             not the 1M beta; got {}",
            m.context_window,
        );
        assert!(m.max_tokens > 0);
    }

    #[test]
    fn find_nonexistent_model_returns_none() {
        let catalog = Catalog::new();
        assert!(catalog.find("nonexistent/model-id").is_none());
    }

    #[test]
    fn by_provider_returns_subset() {
        let catalog = Catalog::new();
        let anthropic = catalog.by_provider("anthropic");
        assert!(!anthropic.is_empty());
        for m in &anthropic {
            assert_eq!(m.provider, "anthropic");
        }
    }

    #[test]
    fn search_finds_by_id() {
        let catalog = Catalog::new();
        let results = catalog.search("claude-sonnet");
        assert!(!results.is_empty());
    }

    #[test]
    fn search_finds_by_name() {
        let catalog = Catalog::new();
        let results = catalog.search("Claude");
        assert!(!results.is_empty());
    }

    #[test]
    fn search_empty_returns_all() {
        let catalog = Catalog::new();
        assert_eq!(catalog.search("").len(), catalog.models().len());
    }

    #[test]
    fn with_user_models_adds_new() {
        let catalog = Catalog::with_user_models(vec![Model {
            id: "my-custom/model".to_string(),
            name: "My Custom Model".to_string(),
            provider: "custom".to_string(),
            context_window: 4096,
            max_tokens: 1024,
            input: ModelInput::default(),
            cost: ModelCost::default(),
            thinking: ModelThinking::default(),
        }]);
        assert!(catalog.find("my-custom/model").is_some());
    }

    #[test]
    fn with_user_models_replaces_existing() {
        let catalog = Catalog::with_user_models(vec![Model {
            id: "anthropic/claude-sonnet-4".to_string(),
            name: "OVERRIDDEN".to_string(),
            provider: "custom".to_string(),
            context_window: 1,
            max_tokens: 1,
            input: ModelInput::default(),
            cost: ModelCost::default(),
            thinking: ModelThinking::default(),
        }]);
        let m = catalog.find("anthropic/claude-sonnet-4").unwrap();
        assert_eq!(m.name, "OVERRIDDEN");
        assert_eq!(m.provider, "custom");
    }

    // ── cost computation ───────────────────────────────────────────────

    #[test]
    fn cost_for_known_model_matches_per_million_pricing() {
        // Derive the expected cost from the catalog itself so the test
        // survives catalog regenerations (OpenRouter prices change often).
        let model = Catalog::find_built_in("z-ai/glm-5.2").expect("glm-5.2 present");
        let usage = StreamUsage::new(1_000_000, 500_000);
        let cost = model.cost_for(&usage).expect("pricing available");
        let expected = model.cost.input + 0.5 * model.cost.output;
        assert!(
            (cost - expected).abs() < 1e-9,
            "got {cost}, expected {expected}"
        );
    }

    #[test]
    fn cost_for_prices_cached_reads_at_discount() {
        let model = Catalog::find_built_in("z-ai/glm-5.2").expect("glm-5.2 present");
        let usage = StreamUsage::new(1_000_000, 0).with_cached(1_000_000);
        let cost = model.cost_for(&usage).expect("pricing available");
        // All input cached: 1M @ cache_read. Fall back to the input rate when
        // the catalog reports no cache_read, mirroring `cost_for`'s contract.
        let cache_rate = if model.cost.cache_read > 0.0 {
            model.cost.cache_read
        } else {
            model.cost.input
        };
        assert!(
            (cost - cache_rate).abs() < 1e-9,
            "got {cost}, expected {cache_rate}"
        );
    }

    #[test]
    fn cost_for_returns_none_for_sentinel_pricing() {
        // openrouter/auto carries OpenRouter's "-1" sentinel → -1_000_000.
        let model = Catalog::find_built_in("openrouter/auto").expect("router present");
        let usage = StreamUsage::new(1_000, 500);
        assert!(
            model.cost_for(&usage).is_none(),
            "sentinel must not yield a cost"
        );
    }

    #[test]
    fn cost_for_missing_cache_read_falls_back_to_input_rate() {
        // A model with a real input/output price but no cache_read reported.
        let cost = ModelCost {
            input: 2.0,
            output: 6.0,
            cache_read: 0.0,
            cache_write: 0.0,
        };
        // 500k fresh + 500k cached, no output. Without fallback the cached
        // half would be free ($0.5); with fallback both price at input.
        let usage = StreamUsage::new(1_000_000, 0).with_cached(500_000);
        let total = cost.cost_for(&usage).unwrap();
        assert!((total - 2.0).abs() < 1e-9, "got {total}");
    }

    #[test]
    fn find_built_in_does_not_allocate_catalog() {
        // Smoke test: the static lookup returns a stable reference.
        let a = Catalog::find_built_in("anthropic/claude-sonnet-4");
        let b = Catalog::find_built_in("anthropic/claude-sonnet-4");
        assert!(std::ptr::eq(a.unwrap(), b.unwrap()));
    }

    // ── pricing eligibility + native-id resolution ───────────────────────

    #[test]
    fn is_priced_true_for_real_pricing() {
        let cost = ModelCost {
            input: 1.0,
            output: 2.0,
            cache_read: 0.5,
            cache_write: 1.0,
        };
        assert!(cost.is_priced());
    }

    #[test]
    fn is_priced_false_for_sentinel_pricing() {
        // OpenRouter sentinel: negative prices mean "unknown".
        let cost = ModelCost {
            input: -1.0,
            output: -1.0,
            cache_read: 0.0,
            cache_write: 0.0,
        };
        assert!(!cost.is_priced());
    }

    #[test]
    fn resolve_exact_openrouter_id() {
        let m = Catalog::resolve(None, "openai/gpt-4o-2024-08-06").expect("exact id present");
        assert_eq!(m.provider, "openai");
    }

    #[test]
    fn resolve_bare_basename_unique_matches_provider_entry() {
        // A native provider sends the bare id; resolve it via basename.
        let m = Catalog::resolve(None, "gpt-4o-2024-08-06").expect("basename should resolve");
        assert_eq!(m.id, "openai/gpt-4o-2024-08-06");
        assert_eq!(m.provider, "openai");
    }

    #[test]
    fn resolve_bare_native_id_carries_full_context_window() {
        // Concrete regression: a bare native id (no `provider/` prefix) must
        // resolve to its catalog entry with the real context window, not be
        // missed by exact-only lookup. `deepseek-v4-flash` is a 1M-window
        // model; exact `find_built_in` does not match the bare id, which is
        // why budget resolution must use `resolve` (basename-aware).
        let m = Catalog::resolve(None, "deepseek-v4-flash").expect("bare id should resolve");
        assert_eq!(m.id, "deepseek/deepseek-v4-flash");
        assert_eq!(m.context_window, 1_048_576);
        // Documents the gap: exact-only lookup misses the bare id.
        assert!(Catalog::find_built_in("deepseek-v4-flash").is_none());
    }

    #[test]
    fn resolve_unknown_id_is_none() {
        assert!(Catalog::resolve(None, "no-such-vendor/totally-made-up-model").is_none());
        assert!(Catalog::resolve(None, "totally-made-up-bare-id").is_none());
    }

    #[test]
    fn resolve_sentinel_basename_is_filtered() {
        // `openrouter/auto` is a sentinel router entry; its basename `auto`
        // must not resolve (it would yield no usable pricing).
        assert!(Catalog::resolve(None, "auto").is_none());
    }

    // ── resolve_in with synthetic models (disambiguation paths) ─────────

    /// A realistically-priced synthetic model.
    fn priced(id: &str, provider: &str) -> Model {
        Model {
            id: id.to_string(),
            name: id.to_string(),
            provider: provider.to_string(),
            context_window: 128_000,
            max_tokens: 4_096,
            input: ModelInput::default(),
            cost: ModelCost {
                input: 1.0,
                output: 2.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            thinking: ModelThinking::default(),
        }
    }

    /// A sentinel-priced synthetic model (`OpenRouter` "-1" convention).
    fn sentinel(id: &str, provider: &str) -> Model {
        Model {
            cost: ModelCost {
                input: -1.0,
                output: -1.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            ..priced(id, provider)
        }
    }

    #[test]
    fn resolve_in_exact_takes_precedence() {
        let models = vec![priced("openai/gpt-4o", "openai")];
        assert!(Catalog::resolve_in(None, "openai/gpt-4o", &models).is_some());
    }

    #[test]
    fn resolve_in_ambiguous_basename_without_hint_is_none() {
        let models = vec![priced("alpha/dupe", "alpha"), priced("beta/dupe", "beta")];
        assert!(Catalog::resolve_in(None, "dupe", &models).is_none());
    }

    #[test]
    fn resolve_in_ambiguous_basename_with_correct_hint_resolves() {
        let models = vec![priced("alpha/dupe", "alpha"), priced("beta/dupe", "beta")];
        let m = Catalog::resolve_in(Some("beta"), "dupe", &models).expect("hint disambiguates");
        assert_eq!(m.provider, "beta");
    }

    #[test]
    fn resolve_in_ambiguous_basename_with_wrong_hint_is_none() {
        let models = vec![priced("alpha/dupe", "alpha"), priced("beta/dupe", "beta")];
        assert!(Catalog::resolve_in(Some("gamma"), "dupe", &models).is_none());
    }

    #[test]
    fn resolve_in_skips_solo_sentinel_basename() {
        // Only a sentinel entry shares the basename → filtered → None.
        let models = vec![sentinel("solo/special", "solo")];
        assert!(Catalog::resolve_in(None, "special", &models).is_none());
    }

    #[test]
    fn resolve_in_prefers_priced_over_sentinel_sharing_basename() {
        // The sentinel is filtered, leaving one priced hit → resolves to beta.
        let models = vec![sentinel("alpha/dupe", "alpha"), priced("beta/dupe", "beta")];
        let m = Catalog::resolve_in(None, "dupe", &models).expect("priced entry resolves");
        assert_eq!(m.provider, "beta");
    }
}
