//! Model catalog — built-in model registry and user-configurable extensions.
//!
//! The built-in models are generated by `cargo xtask generate-models` from
//! OpenRouter's public model list, with manual overrides for thinking support
//! and compatibility flags stored in `rho-ai/model-overrides.json`.
//!
//! Users can extend or override the built-in catalog via provider config in
//! `~/.rho/config.toml` (dedicated subscriptions, local models, etc.).

/// Cost information for a model, in USD per million tokens.
#[derive(Debug, Clone, Default)]
pub struct ModelCost {
    /// Cost per million input tokens.
    pub input: f64,
    /// Cost per million output (completion) tokens.
    pub output: f64,
    /// Cost per million cached-read input tokens (prompt caching).
    pub cache_read: f64,
    /// Cost per million cache-write input tokens (prompt caching).
    pub cache_write: f64,
}

/// Input modalities supported by a model.
#[derive(Debug, Clone, Default)]
pub struct ModelInput {
    pub text: bool,
    pub image: bool,
}

/// Thinking/reasoning capability of a model.
#[derive(Debug, Clone, Default)]
pub struct ModelThinking {
    /// Whether this model supports extended thinking / chain-of-thought.
    pub supported: bool,
    /// How to request thinking from this model (e.g. `"reasoning"`, `"reasoning_effort"`).
    /// `None` means the default provider behavior.
    pub format: Option<String>,
}

/// A single model entry in the catalog.
#[derive(Debug, Clone)]
pub struct Model {
    /// Unique model identifier (e.g. `"anthropic/claude-sonnet-4"`).
    pub id: String,
    /// Human-readable display name (e.g. `"Claude Sonnet 4"`).
    pub name: String,
    /// Provider slug (e.g. `"anthropic"`, `"openai"`, `"deepseek"`).
    pub provider: String,
    /// Maximum context window in tokens.
    pub context_window: u64,
    /// Maximum completion (output) tokens per request.
    pub max_tokens: u64,
    /// Supported input modalities.
    pub input: ModelInput,
    /// Cost per million tokens.
    pub cost: ModelCost,
    /// Thinking/reasoning capability.
    pub thinking: ModelThinking,
}

/// Default model used when nothing is configured and `RHO_MODEL` is not set.
///
/// Picked as the best general-purpose coding model available via OpenRouter.
pub const DEFAULT_MODEL_ID: &str = "anthropic/claude-sonnet-4";

/// The model catalog — built-in models plus optional user extensions.
#[derive(Debug, Clone)]
pub struct Catalog {
    models: Vec<Model>,
}

impl Catalog {
    /// Create a catalog from the built-in model list only.
    pub fn new() -> Self {
        Self {
            models: crate::catalog_generated::built_in_models(),
        }
    }

    /// Create a catalog with additional user-defined models merged on top.
    ///
    /// User models with the same `id` replace built-in entries.
    pub fn with_user_models(user_models: Vec<Model>) -> Self {
        let mut models = crate::catalog_generated::built_in_models();
        for user in user_models {
            if let Some(existing) = models.iter_mut().find(|m| m.id == user.id) {
                *existing = user;
            } else {
                models.push(user);
            }
        }
        Self { models }
    }

    /// All models in the catalog.
    pub fn models(&self) -> &[Model] {
        &self.models
    }

    /// Find a model by its exact ID.
    pub fn find(&self, id: &str) -> Option<&Model> {
        self.models.iter().find(|m| m.id == id)
    }

    /// Find models by provider slug.
    pub fn by_provider(&self, provider: &str) -> Vec<&Model> {
        self.models
            .iter()
            .filter(|m| m.provider == provider)
            .collect()
    }

    /// Search models by a case-insensitive substring match on ID or name.
    pub fn search(&self, query: &str) -> Vec<&Model> {
        let query = query.to_lowercase();
        self.models
            .iter()
            .filter(|m| m.id.to_lowercase().contains(&query) || m.name.to_lowercase().contains(&query))
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_contains_models() {
        let catalog = Catalog::new();
        assert!(!catalog.models().is_empty());
    }

    #[test]
    fn find_existing_model() {
        let catalog = Catalog::new();
        // Pick a model we know exists in OpenRouter.
        let model = catalog.find("anthropic/claude-sonnet-4");
        assert!(model.is_some());
        let m = model.unwrap();
        assert_eq!(m.provider, "anthropic");
        assert!(m.context_window > 0);
    }

    #[test]
    fn find_nonexistent_model_returns_none() {
        let catalog = Catalog::new();
        assert!(catalog.find("nonexistent/model-id").is_none());
    }

    #[test]
    fn by_provider_returns_subset() {
        let catalog = Catalog::new();
        let anthropic = catalog.by_provider("anthropic");
        assert!(!anthropic.is_empty());
        for m in &anthropic {
            assert_eq!(m.provider, "anthropic");
        }
    }

    #[test]
    fn search_finds_by_id() {
        let catalog = Catalog::new();
        let results = catalog.search("claude-sonnet");
        assert!(!results.is_empty());
    }

    #[test]
    fn search_finds_by_name() {
        let catalog = Catalog::new();
        let results = catalog.search("Claude");
        assert!(!results.is_empty());
    }

    #[test]
    fn search_empty_returns_all() {
        let catalog = Catalog::new();
        assert_eq!(catalog.search("").len(), catalog.models().len());
    }

    #[test]
    fn with_user_models_adds_new() {
        let catalog = Catalog::with_user_models(vec![Model {
            id: "my-custom/model".to_string(),
            name: "My Custom Model".to_string(),
            provider: "custom".to_string(),
            context_window: 4096,
            max_tokens: 1024,
            input: ModelInput::default(),
            cost: ModelCost::default(),
            thinking: ModelThinking::default(),
        }]);
        assert!(catalog.find("my-custom/model").is_some());
    }

    #[test]
    fn with_user_models_replaces_existing() {
        let catalog = Catalog::with_user_models(vec![Model {
            id: "anthropic/claude-sonnet-4".to_string(),
            name: "OVERRIDDEN".to_string(),
            provider: "custom".to_string(),
            context_window: 1,
            max_tokens: 1,
            input: ModelInput::default(),
            cost: ModelCost::default(),
            thinking: ModelThinking::default(),
        }]);
        let m = catalog.find("anthropic/claude-sonnet-4").unwrap();
        assert_eq!(m.name, "OVERRIDDEN");
        assert_eq!(m.provider, "custom");
    }
}
