[package]
name = "rho-test-helpers"
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
futures.workspace = true
rho-core = { path = "../rho-core" }
rho-ai = { path = "../rho-ai" }
serde_json.workspace = true
tempfile = "3"
tokio.workspace = true
which = "8.0.4"
