[package]
name = "rho-tools"
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
categories.workspace = true

[lints]
workspace = true

[dev-dependencies]
dunce = "1"
rho-test-helpers = { path = "../rho-test-helpers" }
tempfile = "3"

[dependencies]
async-trait.workspace = true
globset = "0.4"
grep-regex = "0.1"
grep-searcher = "0.1"
ignore = "0.4"
reqwest = { version = "0.13", features = ["json"] }
rho-core = { path = "../rho-core" }
rho-highlight = { path = "../rho-highlight" }
rho-memory = { path = "../rho-memory" }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tree-sitter.workspace = true
url = "2.5"
uuid.workspace = true
which = "8.0.4"
